### ISSUE TITLE
你好，想向你请教几个问题

### ISSUE THREAD

**Issue by baobin81** [qiusihang/pano2photo#1]
你好，能不能留个联系方式，我在看你写的代码，理解有点困难。能不能指导一下。

**Comment by baobin81** [comment]
我的电话是：13311308891
微信是：baobin1234

**Comment by baobin81** [comment]
期待你回复，谢谢。

**Comment by qiusihang** [comment]
你好, 我的email: s.qiu-1@tudelft.nl

**Comment by baobin81** [comment]
你方便时间，能不能把 function convert(panodata, img, heading, pitch, fov) 这个函数，写个注解。从数学公式的角度。

**Comment by qiusihang** [comment]
> 你方便时间，能不能把 function convert(panodata, img, heading, pitch, fov) 这个函数，写个注解。从数学公式的角度。

註釋已添加

**Comment by baobin81** [comment]
谢谢，辛苦了。
